Repository NehangPatel23/FinTrackr, pull requests merged in 2025-02, with the labels that each got.

#18 tax page edited
  .DS_Store
  Code/assets/expenses-removebg-preview.png
  Code/lib/screens/add_expense/views/add_expense.dart
  Code/lib/screens/home/views/home_screen.dart
  Code/lib/screens/taxes/taxes_page.dart
Labels: enhancement

#19 tax page minus pie chart
  Code/lib/screens/taxes/taxes_page.dart
Labels: enhancement

#23 minor ui fixes and code structure enhancements
  Code/lib/screens/add_expense/views/add_expense.dart
  Code/lib/screens/debt/views/debt_page.dart
  Code/lib/screens/home/views/main_screen.dart
  Code/lib/screens/taxes/taxes_page.dart
  Code/lib/screens/ui_elements/dropdown.dart
  Code/lib/screens/ui_elements/info_dialog.dart
  Code/lib/screens/ui_elements/question_row.dart
  Code/lib/screens/ui_elements/text_field.dart
Labels: enhancement

#24 Update Milestones.md
  Milestones.md
  README.md
Labels: documentation

#25 tax page fixes
  .DS_Store
  Code/assets/tax_calculation.png
  Code/assets/tax_info_page.png
  Code/lib/screens/add_expense/views/add_expense.dart
  Code/lib/screens/debt/views/debt_page.dart
  Code/lib/screens/taxes/tax_results.dart
  Code/lib/screens/taxes/taxes_page.dart
  Code/lib/screens/ui_elements/header.dart
Labels: enhancement, fixed code

#31 added pages for settings
  .DS_Store
  .idea/libraries/Dart_Packages.xml
  Code/assets/contact_us.png
  Code/assets/faq.png
  Code/assets/info.png
  Code/assets/nehang.png
  Code/assets/shruti.png
  Code/assets/tharun.png
  Code/ios/Podfile.lock
  Code/lib/screens/settings/about_page.dart
  Code/lib/screens/settings/contact_page.dart
  Code/lib/screens/settings/faq_page.dart
  Code/lib/screens/settings/settings_page.dart
  Code/linux/flutter/generated_plugin_registrant.cc
  Code/linux/flutter/generated_plugins.cmake
  Code/macos/Flutter/GeneratedPluginRegistrant.swift
  Code/pubspec.yaml
  Code/windows/flutter/generated_plugin_registrant.cc
  Code/windows/flutter/generated_plugins.cmake
Labels: enhancement

#32 balance card updates
  .DS_Store
  Code/lib/screens/add_expense/views/add_expense.dart
  Code/lib/screens/home/views/main_screen.dart
  Code/packages/expense_repository/lib/src/entities/expense_entity.dart
  Code/packages/expense_repository/lib/src/models/expense.dart
  Code/pubspec.yaml
Labels: enhancement, fixed code

#34 Bug fixes, phase 1
  .idea/caches/deviceStreaming.xml
Labels: enhancement, fixed code

#39 fixed transactions list bug and minor UI changes to main screen
  Code/lib/data/data.dart
  Code/lib/screens/add_expense/blocs/get_categories/get_categories_bloc.dart
  Code/lib/screens/home/blocs/get_expenses_bloc.dart
  Code/lib/screens/home/views/main_screen.dart
  Code/packages/expense_repository/lib/src/expense_repo.dart
  Code/packages/expense_repository/lib/src/firebase_expense_repo.dart
Labels: enhancement, fixed code
